language: c

services:
        - docker

script:
        - docker build -t idodin/techgames-challenge-ui:latest .

dploy:
        provider: script
        script: bash docker_push
        on:
                branch: master
